apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-frontend
  template:
    metadata:
      labels:
        app: health-frontend
    spec:
      containers:
        - name: frontend
          image: rubeenabegum/frontend:v3
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: health-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: health-frontend
  ports:
    - port: 80
      targetPort: 3000
